import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage { en, ar }

class AppSettingsController extends ChangeNotifier {
  static const _themeKey = 'theme_mode';

  ThemeMode _themeMode = ThemeMode.light;
  final AppLanguage _language = AppLanguage.ar;

  ThemeMode get themeMode => _themeMode;
  AppLanguage get language => _language;
  Locale get locale => const Locale('ar');
  TextDirection get textDirection => TextDirection.rtl;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final savedTheme = prefs.getString(_themeKey);
    _themeMode = savedTheme == 'dark' ? ThemeMode.dark : ThemeMode.light;
    notifyListeners();
  }

  Future<void> setThemeMode(ThemeMode mode) async {
    _themeMode = mode;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_themeKey, mode == ThemeMode.dark ? 'dark' : 'light');
  }
}

class AppSettingsScope extends InheritedNotifier<AppSettingsController> {
  const AppSettingsScope({
    super.key,
    required AppSettingsController controller,
    required super.child,
  }) : super(notifier: controller);

  static AppSettingsController of(BuildContext context) {
    final scope =
        context.dependOnInheritedWidgetOfExactType<AppSettingsScope>();
    assert(scope != null, 'AppSettingsScope was not found in the widget tree.');
    return scope!.notifier!;
  }
}

extension AppSettingsX on BuildContext {
  AppSettingsController get settings => AppSettingsScope.of(this);
  String t(String key) => AppStrings.translate(settings.language, key);
  String statusText(String status) =>
      AppStrings.translate(settings.language, 'status_$status');
}

class AppStrings {
  const AppStrings._();

  static const _en = <String, String>{
    'admin': 'Admin',
    'unknown': 'Unknown',
    'trips_label': 'trips',
    'menu': 'Menu',
    'settings': 'Settings',
    'support': 'Support',
    'support_center': 'Support center',
    'support_request': 'Support request',
    'report_problem': 'Report a problem',
    'payment_issue': 'Payment issue',
    'ticket_type': 'Ticket type',
    'support_message': 'Describe what happened',
    'support_sent': 'Your message was sent.',
    'send': 'Send',
    'message_too_short': 'Write at least 12 characters',
    'privacy_policy': 'Privacy policy',
    'terms': 'Terms',
    'legal': 'Legal',
    'privacy_1':
        'Veloce Express stores the account information needed to run deliveries: name, email, phone number, role, orders, bids, ratings, and support messages.',
    'privacy_2':
        'Driver vehicle photos are stored in Firestore as compressed Base64 data because Firebase Storage is not used in this version.',
    'privacy_3':
        'Location data is only used for active delivery operations and may be visible to the matched client or driver during the trip.',
    'privacy_4':
        'Users can request support or report a problem from inside the app. Admins can review tickets to protect the service.',
    'terms_1':
        'Users must provide correct account, phone, delivery address, and order information.',
    'terms_2':
        'Drivers are responsible for submitting realistic bids and confirming delivery only after handing the item to the client.',
    'terms_3':
        'Clients are responsible for accepting a bid only when they agree with the price and details.',
    'terms_4':
        'Admins may approve, block, or review accounts and tickets to protect Veloce Express users.',
    'account_settings': 'Account settings',
    'appearance': 'Appearance',
    'light': 'Light',
    'dark': 'Dark',
    'language': 'Language',
    'english': 'English',
    'arabic': 'Arabic',
    'sign_out': 'Sign out',
    'account_info': 'Account information',
    'full_name': 'Full name',
    'email': 'Email',
    'phone': 'Phone number',
    'new_password': 'New password',
    'leave_blank': 'Leave blank to keep current password',
    'save_changes': 'Save changes',
    'saved': 'Changes saved.',
    'reauth_required': 'For email/password changes, sign in again then retry.',
    'jobs_near_you': 'Jobs near you',
    'my_orders': 'My orders',
    'new_order': 'New Order',
    'choose_driver': 'Choose driver',
    'driver_profile': 'Driver profile',
    'driver_not_found': 'Driver not found',
    'send_delivery_request': 'Send delivery request',
    'choose_driver_first': 'Choose a driver first',
    'choose_driver_first_body':
        'Delivery requests are sent to one selected driver.',
    'no_drivers': 'No drivers available',
    'no_drivers_body': 'Approved drivers will appear here.',
    'my_delivery_requests': 'My delivery requests',
    'no_driver_requests': 'No direct requests',
    'no_driver_requests_body': 'Requests sent to you will appear here.',
    'delivery_request': 'Delivery request',
    'delivery_price': 'Delivery price',
    'send_price': 'Send price',
    'price_sent': 'Price sent',
    'driver_sent_price': 'Driver sent a delivery price',
    'waiting_driver_price': 'Waiting for driver price',
    'price_rejected': 'Price rejected',
    'client_rejected_price':
        'The client rejected your price. You can send a new price.',
    'new_delivery_price': 'New delivery price',
    'client_cancelled_order': 'The client cancelled this order.',
    'confirm_delivery_received': 'Confirm delivery received',
    'confirm_delivery_body': 'Confirm only after receiving your delivery.',
    'dashboard': 'Dashboard',
    'users': 'Users',
    'clients': 'Clients',
    'drivers': 'Drivers',
    'stores': 'Stores',
    'all': 'All',
    'no_users': 'No users',
    'no_users_found': 'No users found.',
    'create_order': 'Create Order',
    'order': 'Order',
    'place_bid': 'Place Bid',
    'back': 'Back',
    'sign_in_subtitle': 'Sign in to manage deliveries and bids.',
    'sign_in': 'Sign In',
    'create_account': 'Create account',
    'already_have_account': 'I already have an account',
    'client': 'Client',
    'driver': 'Driver',
    'store': 'Store',
    'store_type': 'Store type',
    'restaurant': 'Restaurant',
    'grocery': 'Grocery',
    'other': 'Other',
    'store_address': 'Store address',
    'upload_store_photo': 'Upload store photo',
    'store_photo_required': 'Store photo is required',
    'store_photo': 'Store photo',
    'password': 'Password',
    'vehicle': 'Vehicle',
    'bike': 'Bike',
    'car': 'Car',
    'truck': 'Truck',
    'motorcycle': 'Motorcycle',
    'upload_vehicle_photo': 'Upload vehicle photo',
    'vehicle_photo_required': 'Vehicle photo is required for drivers',
    'contact_phone': 'Contact phone',
    'describe_item': 'Describe the item',
    'description': 'Description',
    'publish_request': 'Publish Request',
    'pickup_address': 'Pickup address',
    'dropoff_address': 'Drop-off address',
    'delivery_address': 'Delivery address',
    'delivery_address_hint': 'Where should the order be delivered?',
    'active_trip_missing': 'Trip data missing',
    'page_not_found': 'Page not found',
    'open_dashboard': 'Open dashboard',
    'return_active_trip': 'Return to active trip',
    'algerian_phone_error': 'Enter a valid Algerian mobile number',
    'field_required': 'This field is required',
    'valid_email': 'Enter a valid email',
    'password_length': 'Use at least 6 characters',
    'accepted_fare': 'Accepted fare',
    'leave_comment': 'Leave a comment (optional)',
    'status_open': 'Open',
    'status_storePending': 'At restaurant',
    'status_requested': 'Requested',
    'status_priced': 'Priced',
    'status_bidding': 'Bidding',
    'status_accepted': 'Accepted',
    'status_inProgress': 'In progress',
    'status_delivered': 'Delivered',
    'status_cancelled': 'Cancelled',
    'status_pending': 'Pending',
    'status_rejected': 'Rejected',
    'pickup': 'Pickup',
    'dropoff': 'Drop-off',
    'from': 'From',
    'to': 'To',
    'bids': 'Bids',
    'no_orders_yet': 'No orders yet',
    'create_first_order': 'Create your first Veloce Express request.',
    'order_not_found': 'Order not found',
    'order_missing': 'This request no longer exists.',
    'no_bids_yet': 'No bids yet',
    'drivers_bid_realtime': 'Approved drivers will bid in real time.',
    'rating': 'Rating',
    'reject': 'Reject',
    'accept': 'Accept',
    'bid_amount': 'Bid amount',
    'amount': 'Amount',
    'valid_amount': 'Enter a valid amount',
    'send_bid': 'Send Bid',
    'no_jobs_available': 'No jobs available',
    'open_requests_appear': 'Open Veloce Express requests will appear here.',
    'active_trip': 'Active trip',
    'you': 'You',
    'live': 'LIVE',
    'in_transit': 'In transit',
    'driver_en_route': 'Driver en route',
    'your_driver': 'Your Driver',
    'agreed_fare': 'Agreed Fare',
    'confirm_trip': 'Confirm Trip',
    'trip_completed': 'Trip completed.',
    'leave_active_trip': 'Leave active trip?',
    'leave_active_trip_body':
        'The trip is still in progress. You can return to it anytime.',
    'stay': 'Stay',
    'leave': 'Leave',
    'confirm_trip_question': 'Confirm Trip?',
    'confirm_trip_body': 'Confirm only after handing the item to the client.',
    'yes_completed': 'Yes, Completed',
    'cancel': 'Cancel',
    'cancel_order': 'Cancel order',
    'cancel_reason': 'Cancellation reason',
    'cancelled_by': 'Cancelled by',
    'order_cancelled': 'Order cancelled.',
    'address_too_short': 'Write a clearer address',
    'addresses_must_differ': 'Write a clear delivery address',
    'rate_experience': 'Rate your experience',
    'how_was': 'How was',
    'submit_rating': 'Submit Rating',
    'skip': 'Skip',
    'approvals': 'Approvals',
    'orders': 'Orders',
    'all_caught_up': 'All caught up!',
    'no_pending_approvals': 'No pending approvals.',
    'vehicle_photo': 'Vehicle Photo',
    'approve': 'Approve',
    'no_orders': 'No orders',
    'orders_empty': 'Your orders will appear here.',
    'no_orders_filter': 'No orders match this filter.',
    'approved': 'Approved',
    'blocked': 'Blocked',
    'closed': 'Closed',
    'verify_email': 'Verify your email',
    'verify_email_body':
        'We sent a verification link to {email}. The app will continue automatically after verification.',
    'i_verified_email': 'I Verified My Email',
    'resend_email': 'Resend email',
    'waiting_approval': 'Waiting for approval',
    'driver_approval_body':
        'Your account and vehicle photo are under admin review.',
    'client_approval_body': 'Your account is under admin review.',
    'store_approval_body': 'Your store account is under admin review.',
    'refresh_status': 'Refresh Status',
    'driver_dashboard': 'Driver dashboard',
    'client_dashboard': 'Client dashboard',
    'restaurant_dashboard': 'Restaurant dashboard',
    'store_dashboard': 'Restaurant dashboard',
    'store_profile': 'Restaurant profile',
    'store_not_found': 'Store not found',
    'no_stores': 'No stores available',
    'no_stores_body': 'Approved stores will appear here.',
    'call_store': 'Call store',
    'menu_items': 'Menu items',
    'add_menu_item': 'Add menu item',
    'add_first_menu_item': 'Add your first product to the menu.',
    'no_menu_items': 'No menu items',
    'store_menu_empty': 'This store has not added menu items yet.',
    'item_name': 'Item name',
    'item_price': 'Item price',
    'store_orders': 'Store orders',
    'store_orders_empty': 'Orders from clients will appear here.',
    'store_order': 'Store order',
    'send_store_order': 'Send store order',
    'order_notes': 'Order notes',
    'restaurant_products': 'Restaurant products',
    'choose_your_order': 'Choose your order',
    'store_delivery_fee': 'Restaurant delivery fee',
    'delivery_fee_saved': 'Delivery fee saved.',
    'upload_product_photo': 'Upload product photo',
    'quantity': 'Quantity',
    'order_now': 'Order',
    'delivery_fee': 'Delivery fee',
    'products_total': 'Products total',
    'total': 'Total',
    'order_sent_to_restaurant': 'Order sent to the restaurant.',
    'driver_availability': 'Driver availability',
    'available': 'Available',
    'unavailable': 'Unavailable',
    'driver_busy': 'Busy delivering',
    'choose': 'Choose',
    'total_orders': 'Total orders',
    'active_orders': 'Active',
    'completed_orders': 'Completed',
    'total_spent': 'Total spent',
    'total_earned': 'Total earned',
    'available_jobs': 'Available jobs',
    'statistics': 'Statistics',
    'tickets': 'Tickets',
    'no_tickets': 'No support tickets',
    'close_ticket': 'Close ticket',
    'search': 'Search',
    'reported_user': 'Reported user',
    'reported_by': 'Reported by',
    'reply': 'Reply',
    'admin_reply': 'Admin reply',
    'my_tickets': 'My tickets',
    'write_message': 'Write a message',
    'no_messages_yet': 'No messages yet.',
    'reviews': 'Reviews',
    'no_reviews': 'No reviews yet.',
    'comments': 'Comments',
    'no_comments': 'No comments yet.',
    'delete_comment': 'Delete comment',
    'delete': 'Delete',
    'delete_selected': 'Delete selected',
    'select_all': 'Select all',
    'call_driver': 'Call driver',
    'call_logs': 'Calls from app',
    'no_call_logs': 'No calls from the app yet.',
    'called_from_app': 'From app',
    'update_required': 'Update required',
    'update_required_body':
        'A new version is required to continue using Veloce Express.',
    'download_update': 'Download update',
    'image_too_large': 'Image is too large. Choose a smaller photo.',
    'wilaya': 'Wilaya',
    'commune': 'Commune',
    'write_clear_value': 'Write a clear value',
    'products_load_error': 'Products could not be loaded.',
    'search_food_or_restaurant': 'Search food or restaurant',
    'new_restaurant_order': 'New restaurant order',
    'store_delivery_assigned': 'Restaurant delivery assigned',
    'banners': 'Banners',
    'add_banner': 'Add banner',
    'no_banners': 'No banners',
    'add_first_banner': 'Add the first 16:9 banner for the client home.',
    'show_banner': 'Show banner',
    'payments': 'Payments',
    'subscription_settings': 'Subscription settings',
    'no_payments': 'No payments',
    'no_payments_body': 'Subscription receipts will appear here.',
    'subscription_required': 'Subscription required',
    'subscription_required_body':
        'Your free period has ended. Pay the monthly subscription and upload the receipt for admin approval.',
    'baridimob_number': 'BaridiMob number',
    'monthly_fee': 'Monthly fee',
    'upload_payment_receipt': 'Upload payment receipt',
    'send_subscription': 'Send subscription',
    'subscription_sent': 'Payment receipt sent for review.',
    'discover_restaurants': 'Discover nearby restaurants',
    'available_products': 'Available products',
    'fresh_restaurants': 'Fresh meals near you',
    'fresh_restaurants_body':
        'Browse restaurant meals and order delivery with a fixed delivery fee.',
  };

  static const _ar = <String, String>{
    'admin': 'الأدمن',
    'unknown': 'غير معروف',
    'trips_label': 'رحلات',
    'menu': 'القائمة',
    'settings': 'الإعدادات',
    'support': 'الدعم',
    'support_center': 'مركز الدعم',
    'support_request': 'طلب دعم',
    'report_problem': 'الإبلاغ عن مشكلة',
    'payment_issue': 'مشكلة دفع',
    'ticket_type': 'نوع الطلب',
    'support_message': 'اشرح ما حدث',
    'support_sent': 'تم إرسال رسالتك.',
    'send': 'إرسال',
    'message_too_short': 'اكتب 12 حرفاً على الأقل',
    'privacy_policy': 'سياسة الخصوصية',
    'terms': 'الشروط',
    'legal': 'القانونية',
    'privacy_1':
        'يحفظ Veloce Express بيانات الحساب الضرورية لتشغيل التوصيل: الاسم والبريد ورقم الهاتف والدور والطلبات والعروض والتقييمات ورسائل الدعم.',
    'privacy_2':
        'صور مركبات السائقين تحفظ في Firestore بصيغة Base64 مضغوطة لأن Firebase Storage غير مستخدم في هذه النسخة.',
    'privacy_3':
        'بيانات الموقع تستخدم فقط أثناء الرحلات النشطة وقد تظهر للطرف الآخر المرتبط بالرحلة.',
    'privacy_4':
        'يمكن للمستخدمين طلب الدعم أو الإبلاغ عن مشكلة من داخل التطبيق، ويمكن للأدمن مراجعة البلاغات لحماية الخدمة.',
    'terms_1':
        'يجب على المستخدمين إدخال معلومات حساب وهاتف وانطلاق ووصول صحيحة.',
    'terms_2':
        'السائق مسؤول عن إرسال عرض واقعي وتأكيد التسليم فقط بعد تسليم الشيء للزبون.',
    'terms_3':
        'الزبون مسؤول عن قبول العرض فقط عندما يوافق على السعر والتفاصيل.',
    'terms_4':
        'يمكن للأدمن قبول أو حظر الحسابات ومراجعة البلاغات لحماية مستخدمي Veloce Express.',
    'account_settings': 'إعدادات الحساب',
    'appearance': 'المظهر',
    'light': 'نهار',
    'dark': 'داكن',
    'language': 'اللغة',
    'english': 'الإنجليزية',
    'arabic': 'العربية',
    'sign_out': 'تسجيل الخروج',
    'account_info': 'معلومات الحساب',
    'full_name': 'الإسم واللقب',
    'email': 'البريد الإلكتروني',
    'phone': 'رقم الهاتف',
    'new_password': 'كلمة سر جديدة',
    'leave_blank': 'اتركها فارغة للإبقاء على كلمة السر الحالية',
    'save_changes': 'حفظ التغييرات',
    'saved': 'تم حفظ التغييرات.',
    'reauth_required':
        'لتغيير البريد أو كلمة السر، سجل الدخول مرة أخرى ثم أعد المحاولة.',
    'jobs_near_you': 'الطلبات القريبة',
    'my_orders': 'طلباتي',
    'new_order': 'طلب جديد',
    'choose_driver': 'اختيار سائق',
    'driver_profile': 'بروفايل السائق',
    'driver_not_found': 'السائق غير موجود',
    'send_delivery_request': 'إرسال طلب توصيل',
    'choose_driver_first': 'اختر سائقاً أولاً',
    'choose_driver_first_body': 'طلبات التوصيل ترسل إلى سائق محدد واحد.',
    'no_drivers': 'لا يوجد سائقون متاحون',
    'no_drivers_body': 'سيظهر السائقون المقبولون هنا.',
    'my_delivery_requests': 'طلبات التوصيل الخاصة بي',
    'no_driver_requests': 'لا توجد طلبات مباشرة',
    'no_driver_requests_body': 'الطلبات المرسلة إليك ستظهر هنا.',
    'delivery_request': 'طلب توصيل',
    'delivery_price': 'سعر التوصيل',
    'send_price': 'إرسال السعر',
    'price_sent': 'تم إرسال السعر',
    'driver_sent_price': 'السائق أرسل سعر التوصيل',
    'waiting_driver_price': 'في انتظار سعر السائق',
    'price_rejected': 'تم رفض السعر',
    'confirm_delivery_received': 'تأكيد استلام التوصيل',
    'confirm_delivery_body': 'أكد فقط بعد استلام طلبك.',
    'dashboard': 'لوحة التحكم',
    'users': 'المستخدمون',
    'clients': 'الزبائن',
    'drivers': 'السائقون',
    'all': 'الكل',
    'no_users': 'لا يوجد مستخدمون',
    'no_users_found': 'لم يتم العثور على مستخدمين.',
    'create_order': 'إنشاء طلب',
    'order': 'الطلب',
    'place_bid': 'إرسال عرض',
    'back': 'رجوع',
    'sign_in_subtitle': 'سجل الدخول لإدارة الطلبات والعروض.',
    'sign_in': 'تسجيل الدخول',
    'create_account': 'إنشاء حساب',
    'already_have_account': 'لدي حساب بالفعل',
    'client': 'زبون',
    'driver': 'سائق',
    'password': 'كلمة السر',
    'vehicle': 'المركبة',
    'bike': 'دراجة',
    'car': 'سيارة',
    'truck': 'شاحنة',
    'motorcycle': 'دراجة نارية',
    'upload_vehicle_photo': 'رفع صورة المركبة',
    'vehicle_photo_required': 'صورة المركبة مطلوبة للسائقين',
    'contact_phone': 'رقم التواصل',
    'describe_item': 'صف الشيء المراد توصيله',
    'description': 'الوصف',
    'publish_request': 'نشر الطلب',
    'pickup_address': 'مكان الانطلاق',
    'dropoff_address': 'مكان الوصول',
    'delivery_address': 'مكان التوصيل',
    'delivery_address_hint': 'أين تريد توصيل الطلب؟',
    'active_trip_missing': 'بيانات الرحلة غير موجودة',
    'page_not_found': 'الصفحة غير موجودة',
    'open_dashboard': 'فتح لوحة الإحصائيات',
    'return_active_trip': 'العودة إلى الرحلة النشطة',
    'algerian_phone_error': 'أدخل رقم هاتف جزائري صحيح',
    'field_required': 'هذا الحقل مطلوب',
    'valid_email': 'أدخل بريدًا إلكترونيًا صحيحًا',
    'password_length': 'استعمل 6 أحرف على الأقل',
    'accepted_fare': 'السعر المقبول',
    'leave_comment': 'اترك تعليقًا (اختياري)',
    'status_open': 'مفتوح',
    'status_storePending': 'عند المطعم',
    'status_requested': 'مرسل للسائق',
    'status_priced': 'تم إرسال السعر',
    'status_bidding': 'توجد عروض',
    'status_accepted': 'مقبول',
    'status_inProgress': 'قيد التنفيذ',
    'status_delivered': 'تم التسليم',
    'status_cancelled': 'ملغي',
    'status_pending': 'معلق',
    'status_rejected': 'مرفوض',
    'pickup': 'نقطة الانطلاق',
    'dropoff': 'نقطة الوصول',
    'from': 'من',
    'to': 'إلى',
    'bids': 'العروض',
    'no_orders_yet': 'لا توجد طلبات بعد',
    'create_first_order': 'أنشئ أول طلب في Veloce Express.',
    'order_not_found': 'الطلب غير موجود',
    'order_missing': 'هذا الطلب لم يعد موجودًا.',
    'no_bids_yet': 'لا توجد عروض بعد',
    'drivers_bid_realtime': 'ستظهر عروض السائقين المقبولين مباشرة.',
    'rating': 'التقييم',
    'reject': 'رفض',
    'accept': 'قبول',
    'bid_amount': 'قيمة العرض',
    'amount': 'المبلغ',
    'valid_amount': 'أدخل مبلغًا صحيحًا',
    'send_bid': 'إرسال العرض',
    'no_jobs_available': 'لا توجد طلبات متاحة',
    'open_requests_appear': 'ستظهر طلبات Veloce Express المفتوحة هنا.',
    'active_trip': 'رحلة نشطة',
    'you': 'أنت',
    'live': 'مباشر',
    'in_transit': 'قيد التوصيل',
    'driver_en_route': 'السائق في الطريق',
    'your_driver': 'سائقك',
    'agreed_fare': 'السعر المتفق عليه',
    'confirm_trip': 'تأكيد الرحلة',
    'trip_completed': 'تم إكمال الرحلة.',
    'leave_active_trip': 'مغادرة الرحلة النشطة؟',
    'leave_active_trip_body':
        'الرحلة ما زالت قيد التنفيذ. يمكنك العودة إليها لاحقًا.',
    'stay': 'البقاء',
    'leave': 'مغادرة',
    'confirm_trip_question': 'تأكيد الرحلة؟',
    'confirm_trip_body': 'أكد فقط بعد تسليم الشيء إلى الزبون.',
    'yes_completed': 'نعم، تم التسليم',
    'cancel': 'إلغاء',
    'cancel_order': 'إلغاء الطلب',
    'cancel_reason': 'سبب الإلغاء',
    'cancelled_by': 'ألغاه',
    'order_cancelled': 'تم إلغاء الطلب.',
    'address_too_short': 'اكتب عنواناً أوضح',
    'addresses_must_differ': 'مكان الانطلاق والوصول يجب أن يكونا مختلفين',
    'rate_experience': 'قيّم تجربتك',
    'how_was': 'كيف كان',
    'submit_rating': 'إرسال التقييم',
    'skip': 'تخطي',
    'approvals': 'الموافقات',
    'orders': 'الطلبات',
    'all_caught_up': 'كل شيء مكتمل!',
    'no_pending_approvals': 'لا توجد موافقات معلقة.',
    'vehicle_photo': 'صورة المركبة',
    'approve': 'قبول',
    'no_orders': 'لا توجد طلبات',
    'orders_empty': 'ستظهر طلباتك هنا.',
    'no_orders_filter': 'لا توجد طلبات تطابق هذا الفلتر.',
    'approved': 'مقبول',
    'blocked': 'محظور',
    'closed': 'مغلقة',
    'verify_email': 'تحقق من بريدك الإلكتروني',
    'verify_email_body':
        'أرسلنا رابط تحقق إلى {email}. سيكمل التطبيق تلقائيًا بعد التحقق.',
    'i_verified_email': 'تحققت من بريدي',
    'resend_email': 'إعادة إرسال البريد',
    'waiting_approval': 'في انتظار الموافقة',
    'driver_approval_body': 'حسابك وصورة المركبة قيد مراجعة الأدمن.',
    'client_approval_body': 'حسابك قيد مراجعة الأدمن.',
    'refresh_status': 'تحديث الحالة',
    'driver_dashboard': 'لوحة السائق',
    'client_dashboard': 'لوحة الزبون',
    'total_orders': 'كل الطلبات',
    'active_orders': 'نشطة',
    'completed_orders': 'مكتملة',
    'total_spent': 'إجمالي المصروف',
    'total_earned': 'إجمالي الربح',
    'available_jobs': 'الطلبات المتاحة',
    'statistics': 'الإحصائيات',
    'tickets': 'التذاكر',
    'no_tickets': 'لا توجد تذاكر دعم',
    'close_ticket': 'إغلاق التذكرة',
    'search': 'بحث',
    'reported_user': 'المستخدم المبلغ عنه',
    'reported_by':
        '\u0623\u0628\u0644\u063a \u0628\u0648\u0627\u0633\u0637\u0629',
    'reply': '\u0631\u062f',
    'admin_reply': '\u0631\u062f \u0627\u0644\u0623\u062f\u0645\u0646',
    'my_tickets': '\u062a\u0630\u0627\u0643\u0631\u064a',
    'write_message': '\u0627\u0643\u062a\u0628 \u0631\u0633\u0627\u0644\u0629',
    'no_messages_yet':
        '\u0644\u0627 \u062a\u0648\u062c\u062f \u0631\u0633\u0627\u0626\u0644 \u0628\u0639\u062f.',
    'reviews': '\u0627\u0644\u062a\u0639\u0644\u064a\u0642\u0627\u062a',
    'no_reviews':
        '\u0644\u0627 \u062a\u0648\u062c\u062f \u062a\u0639\u0644\u064a\u0642\u0627\u062a \u0628\u0639\u062f.',
    'comments': '\u0627\u0644\u062a\u0639\u0644\u064a\u0642\u0627\u062a',
    'no_comments':
        '\u0644\u0627 \u062a\u0648\u062c\u062f \u062a\u0639\u0644\u064a\u0642\u0627\u062a \u0628\u0639\u062f.',
    'delete_comment':
        '\u062d\u0630\u0641 \u0627\u0644\u062a\u0639\u0644\u064a\u0642',
    'image_too_large':
        '\u0627\u0644\u0635\u0648\u0631\u0629 \u0643\u0628\u064a\u0631\u0629. \u0627\u062e\u062a\u0631 \u0635\u0648\u0631\u0629 \u0623\u0635\u063a\u0631.',
    'client_rejected_price':
        '\u0627\u0644\u0632\u0628\u0648\u0646 \u0631\u0641\u0636 \u0633\u0639\u0631\u0643. \u064a\u0645\u0643\u0646\u0643 \u0625\u0631\u0633\u0627\u0644 \u0633\u0639\u0631 \u062c\u062f\u064a\u062f.',
    'new_delivery_price':
        '\u0633\u0639\u0631 \u0627\u0644\u062a\u0648\u0635\u064a\u0644 \u0627\u0644\u062c\u062f\u064a\u062f',
    'client_cancelled_order':
        '\u0627\u0644\u0632\u0628\u0648\u0646 \u0623\u0644\u063a\u0649 \u0647\u0630\u0627 \u0627\u0644\u0637\u0644\u0628.',
    'delete': '\u062d\u0630\u0641',
    'delete_selected':
        '\u062d\u0630\u0641 \u0627\u0644\u0645\u062d\u062f\u062f',
    'select_all': '\u062a\u062d\u062f\u064a\u062f \u0627\u0644\u0643\u0644',
    'call_driver':
        '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0627\u0644\u0633\u0627\u0626\u0642',
    'call_logs':
        '\u0627\u062a\u0635\u0627\u0644\u0627\u062a \u0645\u0646 \u0627\u0644\u062a\u0637\u0628\u064a\u0642',
    'no_call_logs':
        '\u0644\u0627 \u062a\u0648\u062c\u062f \u0627\u062a\u0635\u0627\u0644\u0627\u062a \u0645\u0646 \u0627\u0644\u062a\u0637\u0628\u064a\u0642 \u0628\u0639\u062f.',
    'called_from_app':
        '\u0645\u0646 \u0627\u0644\u062a\u0637\u0628\u064a\u0642',
    'stores': '\u0627\u0644\u0645\u062d\u0644\u0627\u062a',
    'store': '\u0645\u062d\u0644',
    'store_type': '\u0646\u0648\u0639 \u0627\u0644\u0645\u062d\u0644',
    'restaurant': '\u0645\u0637\u0639\u0645',
    'grocery': '\u0645\u0648\u0627\u062f \u063a\u0630\u0627\u0626\u064a\u0629',
    'other': '\u0623\u062e\u0631\u0649',
    'store_address':
        '\u0639\u0646\u0648\u0627\u0646 \u0627\u0644\u0645\u062d\u0644',
    'upload_store_photo':
        '\u0631\u0641\u0639 \u0635\u0648\u0631\u0629 \u0627\u0644\u0645\u062d\u0644',
    'store_photo_required':
        '\u0635\u0648\u0631\u0629 \u0627\u0644\u0645\u062d\u0644 \u0645\u0637\u0644\u0648\u0628\u0629',
    'store_photo': '\u0635\u0648\u0631\u0629 \u0627\u0644\u0645\u062d\u0644',
    'store_approval_body':
        '\u062d\u0633\u0627\u0628 \u0627\u0644\u0645\u062d\u0644 \u0642\u064a\u062f \u0645\u0631\u0627\u062c\u0639\u0629 \u0627\u0644\u0623\u062f\u0645\u0646.',
    'store_dashboard':
        '\u0644\u0648\u062d\u0629 \u0627\u0644\u0645\u062d\u0644',
    'store_profile':
        '\u0628\u0631\u0648\u0641\u0627\u064a\u0644 \u0627\u0644\u0645\u062d\u0644',
    'store_not_found':
        '\u0627\u0644\u0645\u062d\u0644 \u063a\u064a\u0631 \u0645\u0648\u062c\u0648\u062f',
    'no_stores':
        '\u0644\u0627 \u062a\u0648\u062c\u062f \u0645\u062d\u0644\u0627\u062a \u0645\u062a\u0627\u062d\u0629',
    'no_stores_body':
        '\u0633\u062a\u0638\u0647\u0631 \u0627\u0644\u0645\u062d\u0644\u0627\u062a \u0627\u0644\u0645\u0642\u0628\u0648\u0644\u0629 \u0647\u0646\u0627.',
    'call_store':
        '\u0627\u0644\u0627\u062a\u0635\u0627\u0644 \u0628\u0627\u0644\u0645\u062d\u0644',
    'menu_items': '\u0627\u0644\u0645\u0646\u064a\u0648',
    'add_menu_item': '\u0625\u0636\u0627\u0641\u0629 \u0645\u0646\u062a\u062c',
    'add_first_menu_item':
        '\u0623\u0636\u0641 \u0623\u0648\u0644 \u0645\u0646\u062a\u062c \u0625\u0644\u0649 \u0627\u0644\u0645\u0646\u064a\u0648.',
    'no_menu_items':
        '\u0644\u0627 \u062a\u0648\u062c\u062f \u0645\u0646\u062a\u062c\u0627\u062a',
    'store_menu_empty':
        '\u0647\u0630\u0627 \u0627\u0644\u0645\u062d\u0644 \u0644\u0645 \u064a\u0636\u0641 \u0645\u0646\u062a\u062c\u0627\u062a \u0628\u0639\u062f.',
    'item_name': '\u0627\u0633\u0645 \u0627\u0644\u0645\u0646\u062a\u062c',
    'item_price': '\u0633\u0639\u0631 \u0627\u0644\u0645\u0646\u062a\u062c',
    'store_orders':
        '\u0637\u0644\u0628\u0627\u062a \u0627\u0644\u0645\u062d\u0644',
    'store_orders_empty':
        '\u0637\u0644\u0628\u0627\u062a \u0627\u0644\u0632\u0628\u0627\u0626\u0646 \u0633\u062a\u0638\u0647\u0631 \u0647\u0646\u0627.',
    'store_order': '\u0637\u0644\u0628 \u0645\u0646 \u0645\u062d\u0644',
    'send_store_order':
        '\u0625\u0631\u0633\u0627\u0644 \u0637\u0644\u0628 \u0627\u0644\u0645\u062d\u0644',
    'order_notes':
        '\u0645\u0644\u0627\u062d\u0638\u0627\u062a \u0627\u0644\u0637\u0644\u0628',
    'restaurant_dashboard': 'لوحة المطعم',
    'restaurant_products': 'منتجات المطاعم',
    'choose_your_order': 'اختر طلبك',
    'store_delivery_fee': 'سعر توصيل المطعم',
    'delivery_fee_saved': 'تم حفظ سعر التوصيل.',
    'upload_product_photo': 'رفع صورة المنتج',
    'quantity': 'الكمية',
    'order_now': 'طلب',
    'delivery_fee': 'سعر التوصيل',
    'products_total': 'مجموع المنتجات',
    'total': 'المجموع',
    'order_sent_to_restaurant': 'تم إرسال الطلب إلى المطعم.',
    'driver_availability': 'توفر السائق',
    'available': 'متاح',
    'unavailable': 'غير متاح',
    'driver_busy': 'في توصيلة',
    'choose': 'اختيار',
    'update_required':
        '\u062a\u062d\u062f\u064a\u062b \u0645\u0637\u0644\u0648\u0628',
    'update_required_body':
        '\u064a\u062c\u0628 \u062a\u062d\u0645\u064a\u0644 \u0627\u0644\u0646\u0633\u062e\u0629 \u0627\u0644\u062c\u062f\u064a\u062f\u0629 \u0644\u0645\u062a\u0627\u0628\u0639\u0629 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 Veloce Express.',
    'download_update':
        '\u062a\u062d\u0645\u064a\u0644 \u0627\u0644\u062a\u062d\u062f\u064a\u062b',
    'wilaya': 'الولاية',
    'commune': 'البلدية',
    'write_clear_value': 'اكتب قيمة واضحة',
    'products_load_error': 'تعذر تحميل منتجات المطاعم.',
    'search_food_or_restaurant': 'ابحث عن أكلة أو مطعم',
    'new_restaurant_order': 'طلب جديد من مطعم',
    'store_delivery_assigned': 'تم تعيين توصيلة مطعم',
    'banners': 'الصور',
    'add_banner': 'إضافة صورة',
    'no_banners': 'لا توجد صور',
    'add_first_banner': 'أضف أول صورة علوية بحجم 16:9 لواجهة الزبون.',
    'show_banner': 'إظهار الصورة',
    'payments': 'المدفوعات',
    'subscription_settings': 'إعدادات الاشتراك',
    'no_payments': 'لا توجد مدفوعات',
    'no_payments_body': 'ستظهر وصولات الاشتراك هنا.',
    'subscription_required': 'الاشتراك مطلوب',
    'subscription_required_body':
        'انتهت الفترة المجانية. ادفع الاشتراك الشهري وارفع صورة الوصل ليوافق الأدمن.',
    'baridimob_number': 'رقم بريدي موب',
    'monthly_fee': 'الاشتراك الشهري',
    'upload_payment_receipt': 'رفع صورة الوصل',
    'send_subscription': 'إرسال الاشتراك',
    'subscription_sent': 'تم إرسال وصل الدفع للمراجعة.',
    'discover_restaurants': 'اكتشف مطاعم قريبة منك',
    'available_products': 'المنتجات المتاحة',
    'fresh_restaurants': 'وجبات طازجة قريبة منك',
    'fresh_restaurants_body': 'تصفح وجبات المطاعم واطلب التوصيل بسعر ثابت.',
  };

  static String translate(AppLanguage language, String key) {
    final source = language == AppLanguage.ar ? _ar : _en;
    return source[key] ?? _en[key] ?? key;
  }
}
