import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage { en, ar }

class AppSettingsController extends ChangeNotifier {
  static const _themeKey = 'theme_mode';
  static const _languageKey = 'language_code';

  ThemeMode _themeMode = ThemeMode.light;
  AppLanguage _language = AppLanguage.en;

  ThemeMode get themeMode => _themeMode;
  AppLanguage get language => _language;
  Locale get locale => Locale(_language == AppLanguage.ar ? 'ar' : 'en');
  TextDirection get textDirection =>
      _language == AppLanguage.ar ? TextDirection.rtl : TextDirection.ltr;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final savedTheme = prefs.getString(_themeKey);
    final savedLanguage = prefs.getString(_languageKey);
    _themeMode = savedTheme == 'dark' ? ThemeMode.dark : ThemeMode.light;
    _language = savedLanguage == 'ar' ? AppLanguage.ar : AppLanguage.en;
    notifyListeners();
  }

  Future<void> setThemeMode(ThemeMode mode) async {
    _themeMode = mode;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_themeKey, mode == ThemeMode.dark ? 'dark' : 'light');
  }

  Future<void> setLanguage(AppLanguage language) async {
    _language = language;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(
      _languageKey,
      language == AppLanguage.ar ? 'ar' : 'en',
    );
  }
}

class AppSettingsScope extends InheritedNotifier<AppSettingsController> {
  const AppSettingsScope({
    super.key,
    required AppSettingsController controller,
    required super.child,
  }) : super(notifier: controller);

  static AppSettingsController of(BuildContext context) {
    final scope =
        context.dependOnInheritedWidgetOfExactType<AppSettingsScope>();
    assert(scope != null, 'AppSettingsScope was not found in the widget tree.');
    return scope!.notifier!;
  }
}

extension AppSettingsX on BuildContext {
  AppSettingsController get settings => AppSettingsScope.of(this);
  String t(String key) => AppStrings.translate(settings.language, key);
  String statusText(String status) => AppStrings.translate(
        settings.language,
        'status_$status',
      );
}

class AppStrings {
  const AppStrings._();

  static const _en = <String, String>{
    'admin': 'Admin',
    'unknown': 'Unknown',
    'trips_label': 'trips',
    'menu': 'Menu',
    'settings': 'Settings',
    'support': 'Support',
    'support_center': 'Support center',
    'support_request': 'Support request',
    'report_problem': 'Report a problem',
    'payment_issue': 'Payment issue',
    'ticket_type': 'Ticket type',
    'support_message': 'Describe what happened',
    'support_sent': 'Your message was sent.',
    'send': 'Send',
    'message_too_short': 'Write at least 12 characters',
    'privacy_policy': 'Privacy policy',
    'terms': 'Terms',
    'legal': 'Legal',
    'privacy_1':
        'Veloce Express stores the account information needed to run deliveries: name, email, phone number, role, orders, bids, ratings, and support messages.',
    'privacy_2':
        'Driver vehicle photos are stored in Firestore as compressed Base64 data because Firebase Storage is not used in this version.',
    'privacy_3':
        'Location data is only used for active delivery operations and may be visible to the matched client or driver during the trip.',
    'privacy_4':
        'Users can request support or report a problem from inside the app. Admins can review tickets to protect the service.',
    'terms_1':
        'Users must provide correct account, phone, pickup, and drop-off information.',
    'terms_2':
        'Drivers are responsible for submitting realistic bids and confirming delivery only after handing the item to the client.',
    'terms_3':
        'Clients are responsible for accepting a bid only when they agree with the price and details.',
    'terms_4':
        'Admins may approve, block, or review accounts and tickets to protect Veloce Express users.',
    'account_settings': 'Account settings',
    'appearance': 'Appearance',
    'light': 'Light',
    'dark': 'Dark',
    'language': 'Language',
    'english': 'English',
    'arabic': 'Arabic',
    'sign_out': 'Sign out',
    'account_info': 'Account information',
    'full_name': 'Full name',
    'email': 'Email',
    'phone': 'Phone number',
    'new_password': 'New password',
    'leave_blank': 'Leave blank to keep current password',
    'save_changes': 'Save changes',
    'saved': 'Changes saved.',
    'reauth_required': 'For email/password changes, sign in again then retry.',
    'jobs_near_you': 'Jobs near you',
    'my_orders': 'My orders',
    'new_order': 'New Order',
    'choose_driver': 'Choose driver',
    'driver_profile': 'Driver profile',
    'driver_not_found': 'Driver not found',
    'send_delivery_request': 'Send delivery request',
    'choose_driver_first': 'Choose a driver first',
    'choose_driver_first_body':
        'Delivery requests are sent to one selected driver.',
    'no_drivers': 'No drivers available',
    'no_drivers_body': 'Approved drivers will appear here.',
    'my_delivery_requests': 'My delivery requests',
    'no_driver_requests': 'No direct requests',
    'no_driver_requests_body': 'Requests sent to you will appear here.',
    'delivery_request': 'Delivery request',
    'delivery_price': 'Delivery price',
    'send_price': 'Send price',
    'price_sent': 'Price sent',
    'driver_sent_price': 'Driver sent a delivery price',
    'waiting_driver_price': 'Waiting for driver price',
    'price_rejected': 'Price rejected',
    'confirm_delivery_received': 'Confirm delivery received',
    'confirm_delivery_body': 'Confirm only after receiving your delivery.',
    'dashboard': 'Dashboard',
    'users': 'Users',
    'clients': 'Clients',
    'drivers': 'Drivers',
    'all': 'All',
    'no_users': 'No users',
    'no_users_found': 'No users found.',
    'create_order': 'Create Order',
    'order': 'Order',
    'place_bid': 'Place Bid',
    'back': 'Back',
    'sign_in_subtitle': 'Sign in to manage deliveries and bids.',
    'sign_in': 'Sign In',
    'create_account': 'Create account',
    'already_have_account': 'I already have an account',
    'client': 'Client',
    'driver': 'Driver',
    'password': 'Password',
    'vehicle': 'Vehicle',
    'bike': 'Bike',
    'car': 'Car',
    'truck': 'Truck',
    'motorcycle': 'Motorcycle',
    'upload_vehicle_photo': 'Upload vehicle photo',
    'vehicle_photo_required': 'Vehicle photo is required for drivers',
    'contact_phone': 'Contact phone',
    'describe_item': 'Describe the item',
    'description': 'Description',
    'publish_request': 'Publish Request',
    'pickup_address': 'Pickup address',
    'dropoff_address': 'Drop-off address',
    'active_trip_missing': 'Trip data missing',
    'page_not_found': 'Page not found',
    'open_dashboard': 'Open dashboard',
    'return_active_trip': 'Return to active trip',
    'algerian_phone_error': 'Enter a valid Algerian mobile number',
    'field_required': 'This field is required',
    'valid_email': 'Enter a valid email',
    'password_length': 'Use at least 6 characters',
    'accepted_fare': 'Accepted fare',
    'leave_comment': 'Leave a comment (optional)',
    'status_open': 'Open',
    'status_requested': 'Requested',
    'status_priced': 'Priced',
    'status_bidding': 'Bidding',
    'status_accepted': 'Accepted',
    'status_inProgress': 'In progress',
    'status_delivered': 'Delivered',
    'status_cancelled': 'Cancelled',
    'status_pending': 'Pending',
    'status_rejected': 'Rejected',
    'pickup': 'Pickup',
    'dropoff': 'Drop-off',
    'from': 'From',
    'to': 'To',
    'bids': 'Bids',
    'no_orders_yet': 'No orders yet',
    'create_first_order': 'Create your first Veloce Express request.',
    'order_not_found': 'Order not found',
    'order_missing': 'This request no longer exists.',
    'no_bids_yet': 'No bids yet',
    'drivers_bid_realtime': 'Approved drivers will bid in real time.',
    'rating': 'Rating',
    'reject': 'Reject',
    'accept': 'Accept',
    'bid_amount': 'Bid amount',
    'amount': 'Amount',
    'valid_amount': 'Enter a valid amount',
    'send_bid': 'Send Bid',
    'no_jobs_available': 'No jobs available',
    'open_requests_appear': 'Open Veloce Express requests will appear here.',
    'active_trip': 'Active trip',
    'you': 'You',
    'live': 'LIVE',
    'in_transit': 'In transit',
    'driver_en_route': 'Driver en route',
    'your_driver': 'Your Driver',
    'agreed_fare': 'Agreed Fare',
    'confirm_trip': 'Confirm Trip',
    'trip_completed': 'Trip completed.',
    'leave_active_trip': 'Leave active trip?',
    'leave_active_trip_body':
        'The trip is still in progress. You can return to it anytime.',
    'stay': 'Stay',
    'leave': 'Leave',
    'confirm_trip_question': 'Confirm Trip?',
    'confirm_trip_body': 'Confirm only after handing the item to the client.',
    'yes_completed': 'Yes, Completed',
    'cancel': 'Cancel',
    'cancel_order': 'Cancel order',
    'cancel_reason': 'Cancellation reason',
    'cancelled_by': 'Cancelled by',
    'order_cancelled': 'Order cancelled.',
    'address_too_short': 'Write a clearer address',
    'addresses_must_differ': 'Pickup and drop-off must be different',
    'rate_experience': 'Rate your experience',
    'how_was': 'How was',
    'submit_rating': 'Submit Rating',
    'skip': 'Skip',
    'approvals': 'Approvals',
    'orders': 'Orders',
    'all_caught_up': 'All caught up!',
    'no_pending_approvals': 'No pending approvals.',
    'vehicle_photo': 'Vehicle Photo',
    'approve': 'Approve',
    'no_orders': 'No orders',
    'no_orders_filter': 'No orders match this filter.',
    'approved': 'Approved',
    'blocked': 'Blocked',
    'closed': 'Closed',
    'verify_email': 'Verify your email',
    'verify_email_body':
        'We sent a verification link to {email}. The app will continue automatically after verification.',
    'i_verified_email': 'I Verified My Email',
    'resend_email': 'Resend email',
    'waiting_approval': 'Waiting for approval',
    'driver_approval_body':
        'Your account and vehicle photo are under admin review.',
    'client_approval_body': 'Your account is under admin review.',
    'refresh_status': 'Refresh Status',
    'driver_dashboard': 'Driver dashboard',
    'client_dashboard': 'Client dashboard',
    'total_orders': 'Total orders',
    'active_orders': 'Active',
    'completed_orders': 'Completed',
    'total_spent': 'Total spent',
    'total_earned': 'Total earned',
    'available_jobs': 'Available jobs',
    'statistics': 'Statistics',
    'tickets': 'Tickets',
    'no_tickets': 'No support tickets',
    'close_ticket': 'Close ticket',
    'search': 'Search',
    'reported_user': 'Reported user',
  };

  static const _ar = <String, String>{
    'admin': 'الأدمن',
    'unknown': 'غير معروف',
    'trips_label': 'رحلات',
    'menu': 'القائمة',
    'settings': 'الإعدادات',
    'support': 'الدعم',
    'support_center': 'مركز الدعم',
    'support_request': 'طلب دعم',
    'report_problem': 'الإبلاغ عن مشكلة',
    'payment_issue': 'مشكلة دفع',
    'ticket_type': 'نوع الطلب',
    'support_message': 'اشرح ما حدث',
    'support_sent': 'تم إرسال رسالتك.',
    'send': 'إرسال',
    'message_too_short': 'اكتب 12 حرفاً على الأقل',
    'privacy_policy': 'سياسة الخصوصية',
    'terms': 'الشروط',
    'legal': 'القانونية',
    'privacy_1':
        'يحفظ Veloce Express بيانات الحساب الضرورية لتشغيل التوصيل: الاسم والبريد ورقم الهاتف والدور والطلبات والعروض والتقييمات ورسائل الدعم.',
    'privacy_2':
        'صور مركبات السائقين تحفظ في Firestore بصيغة Base64 مضغوطة لأن Firebase Storage غير مستخدم في هذه النسخة.',
    'privacy_3':
        'بيانات الموقع تستخدم فقط أثناء الرحلات النشطة وقد تظهر للطرف الآخر المرتبط بالرحلة.',
    'privacy_4':
        'يمكن للمستخدمين طلب الدعم أو الإبلاغ عن مشكلة من داخل التطبيق، ويمكن للأدمن مراجعة البلاغات لحماية الخدمة.',
    'terms_1':
        'يجب على المستخدمين إدخال معلومات حساب وهاتف وانطلاق ووصول صحيحة.',
    'terms_2':
        'السائق مسؤول عن إرسال عرض واقعي وتأكيد التسليم فقط بعد تسليم الشيء للزبون.',
    'terms_3':
        'الزبون مسؤول عن قبول العرض فقط عندما يوافق على السعر والتفاصيل.',
    'terms_4':
        'يمكن للأدمن قبول أو حظر الحسابات ومراجعة البلاغات لحماية مستخدمي Veloce Express.',
    'account_settings': 'إعدادات الحساب',
    'appearance': 'المظهر',
    'light': 'نهار',
    'dark': 'داكن',
    'language': 'اللغة',
    'english': 'الإنجليزية',
    'arabic': 'العربية',
    'sign_out': 'تسجيل الخروج',
    'account_info': 'معلومات الحساب',
    'full_name': 'الإسم واللقب',
    'email': 'البريد الإلكتروني',
    'phone': 'رقم الهاتف',
    'new_password': 'كلمة سر جديدة',
    'leave_blank': 'اتركها فارغة للإبقاء على كلمة السر الحالية',
    'save_changes': 'حفظ التغييرات',
    'saved': 'تم حفظ التغييرات.',
    'reauth_required':
        'لتغيير البريد أو كلمة السر، سجل الدخول مرة أخرى ثم أعد المحاولة.',
    'jobs_near_you': 'الطلبات القريبة',
    'my_orders': 'طلباتي',
    'new_order': 'طلب جديد',
    'choose_driver': 'اختيار سائق',
    'driver_profile': 'بروفايل السائق',
    'driver_not_found': 'السائق غير موجود',
    'send_delivery_request': 'إرسال طلب توصيل',
    'choose_driver_first': 'اختر سائقاً أولاً',
    'choose_driver_first_body': 'طلبات التوصيل ترسل إلى سائق محدد واحد.',
    'no_drivers': 'لا يوجد سائقون متاحون',
    'no_drivers_body': 'سيظهر السائقون المقبولون هنا.',
    'my_delivery_requests': 'طلبات التوصيل الخاصة بي',
    'no_driver_requests': 'لا توجد طلبات مباشرة',
    'no_driver_requests_body': 'الطلبات المرسلة إليك ستظهر هنا.',
    'delivery_request': 'طلب توصيل',
    'delivery_price': 'سعر التوصيل',
    'send_price': 'إرسال السعر',
    'price_sent': 'تم إرسال السعر',
    'driver_sent_price': 'السائق أرسل سعر التوصيل',
    'waiting_driver_price': 'في انتظار سعر السائق',
    'price_rejected': 'تم رفض السعر',
    'confirm_delivery_received': 'تأكيد استلام التوصيل',
    'confirm_delivery_body': 'أكد فقط بعد استلام طلبك.',
    'dashboard': 'لوحة التحكم',
    'users': 'المستخدمون',
    'clients': 'الزبائن',
    'drivers': 'السائقون',
    'all': 'الكل',
    'no_users': 'لا يوجد مستخدمون',
    'no_users_found': 'لم يتم العثور على مستخدمين.',
    'create_order': 'إنشاء طلب',
    'order': 'الطلب',
    'place_bid': 'إرسال عرض',
    'back': 'رجوع',
    'sign_in_subtitle': 'سجل الدخول لإدارة الطلبات والعروض.',
    'sign_in': 'تسجيل الدخول',
    'create_account': 'إنشاء حساب',
    'already_have_account': 'لدي حساب بالفعل',
    'client': 'زبون',
    'driver': 'سائق',
    'password': 'كلمة السر',
    'vehicle': 'المركبة',
    'bike': 'دراجة',
    'car': 'سيارة',
    'truck': 'شاحنة',
    'motorcycle': 'دراجة نارية',
    'upload_vehicle_photo': 'رفع صورة المركبة',
    'vehicle_photo_required': 'صورة المركبة مطلوبة للسائقين',
    'contact_phone': 'رقم التواصل',
    'describe_item': 'صف الشيء المراد توصيله',
    'description': 'الوصف',
    'publish_request': 'نشر الطلب',
    'pickup_address': 'مكان الانطلاق',
    'dropoff_address': 'مكان الوصول',
    'active_trip_missing': 'بيانات الرحلة غير موجودة',
    'page_not_found': 'الصفحة غير موجودة',
    'open_dashboard': 'فتح لوحة الإحصائيات',
    'return_active_trip': 'العودة إلى الرحلة النشطة',
    'algerian_phone_error': 'أدخل رقم هاتف جزائري صحيح',
    'field_required': 'هذا الحقل مطلوب',
    'valid_email': 'أدخل بريدًا إلكترونيًا صحيحًا',
    'password_length': 'استعمل 6 أحرف على الأقل',
    'accepted_fare': 'السعر المقبول',
    'leave_comment': 'اترك تعليقًا (اختياري)',
    'status_open': 'مفتوح',
    'status_requested': 'مرسل للسائق',
    'status_priced': 'تم إرسال السعر',
    'status_bidding': 'توجد عروض',
    'status_accepted': 'مقبول',
    'status_inProgress': 'قيد التنفيذ',
    'status_delivered': 'تم التسليم',
    'status_cancelled': 'ملغي',
    'status_pending': 'معلق',
    'status_rejected': 'مرفوض',
    'pickup': 'نقطة الانطلاق',
    'dropoff': 'نقطة الوصول',
    'from': 'من',
    'to': 'إلى',
    'bids': 'العروض',
    'no_orders_yet': 'لا توجد طلبات بعد',
    'create_first_order': 'أنشئ أول طلب في Veloce Express.',
    'order_not_found': 'الطلب غير موجود',
    'order_missing': 'هذا الطلب لم يعد موجودًا.',
    'no_bids_yet': 'لا توجد عروض بعد',
    'drivers_bid_realtime': 'ستظهر عروض السائقين المقبولين مباشرة.',
    'rating': 'التقييم',
    'reject': 'رفض',
    'accept': 'قبول',
    'bid_amount': 'قيمة العرض',
    'amount': 'المبلغ',
    'valid_amount': 'أدخل مبلغًا صحيحًا',
    'send_bid': 'إرسال العرض',
    'no_jobs_available': 'لا توجد طلبات متاحة',
    'open_requests_appear': 'ستظهر طلبات Veloce Express المفتوحة هنا.',
    'active_trip': 'رحلة نشطة',
    'you': 'أنت',
    'live': 'مباشر',
    'in_transit': 'قيد التوصيل',
    'driver_en_route': 'السائق في الطريق',
    'your_driver': 'سائقك',
    'agreed_fare': 'السعر المتفق عليه',
    'confirm_trip': 'تأكيد الرحلة',
    'trip_completed': 'تم إكمال الرحلة.',
    'leave_active_trip': 'مغادرة الرحلة النشطة؟',
    'leave_active_trip_body':
        'الرحلة ما زالت قيد التنفيذ. يمكنك العودة إليها لاحقًا.',
    'stay': 'البقاء',
    'leave': 'مغادرة',
    'confirm_trip_question': 'تأكيد الرحلة؟',
    'confirm_trip_body': 'أكد فقط بعد تسليم الشيء إلى الزبون.',
    'yes_completed': 'نعم، تم التسليم',
    'cancel': 'إلغاء',
    'cancel_order': 'إلغاء الطلب',
    'cancel_reason': 'سبب الإلغاء',
    'cancelled_by': 'ألغاه',
    'order_cancelled': 'تم إلغاء الطلب.',
    'address_too_short': 'اكتب عنواناً أوضح',
    'addresses_must_differ': 'مكان الانطلاق والوصول يجب أن يكونا مختلفين',
    'rate_experience': 'قيّم تجربتك',
    'how_was': 'كيف كان',
    'submit_rating': 'إرسال التقييم',
    'skip': 'تخطي',
    'approvals': 'الموافقات',
    'orders': 'الطلبات',
    'all_caught_up': 'كل شيء مكتمل!',
    'no_pending_approvals': 'لا توجد موافقات معلقة.',
    'vehicle_photo': 'صورة المركبة',
    'approve': 'قبول',
    'no_orders': 'لا توجد طلبات',
    'no_orders_filter': 'لا توجد طلبات تطابق هذا الفلتر.',
    'approved': 'مقبول',
    'blocked': 'محظور',
    'closed': 'مغلقة',
    'verify_email': 'تحقق من بريدك الإلكتروني',
    'verify_email_body':
        'أرسلنا رابط تحقق إلى {email}. سيكمل التطبيق تلقائيًا بعد التحقق.',
    'i_verified_email': 'تحققت من بريدي',
    'resend_email': 'إعادة إرسال البريد',
    'waiting_approval': 'في انتظار الموافقة',
    'driver_approval_body': 'حسابك وصورة المركبة قيد مراجعة الأدمن.',
    'client_approval_body': 'حسابك قيد مراجعة الأدمن.',
    'refresh_status': 'تحديث الحالة',
    'driver_dashboard': 'لوحة السائق',
    'client_dashboard': 'لوحة الزبون',
    'total_orders': 'كل الطلبات',
    'active_orders': 'نشطة',
    'completed_orders': 'مكتملة',
    'total_spent': 'إجمالي المصروف',
    'total_earned': 'إجمالي الربح',
    'available_jobs': 'الطلبات المتاحة',
    'statistics': 'الإحصائيات',
    'tickets': 'التذاكر',
    'no_tickets': 'لا توجد تذاكر دعم',
    'close_ticket': 'إغلاق التذكرة',
    'search': 'بحث',
    'reported_user': 'المستخدم المبلغ عنه',
  };

  static String translate(AppLanguage language, String key) {
    final source = language == AppLanguage.ar ? _ar : _en;
    return source[key] ?? _en[key] ?? key;
  }
}
